### PR TITLE
update contact info -  issue #1018

### PR DESCRIPTION
**Pull request by hoony**
fixed "openbadges@mozilla.org" to "badges@mozillafoundation.org" on terms of uses page.

### CODE REVIEW

**Comment by hoony** [comment]
I've commited about 2 issues #1018 and #1031, but by my mistake all commits are contained on same pull request. 

sorry for that!

**Comment by ottonomy** [comment]
Thanks for the submission, @hoony!

@simonwex Is this a good contact email for the backpack project? (This PR sets a contact email to badges@mozillafoundation.org -- Could you verify that this is still a good address, and if you'd like me to field those requests for the product, feel free to forward that address to badges@badgealliance.org.

I will test the other functionality in this PR as well -- sorting by badge name by default -- and verify some edge cases, then I'll try to give my plus1 recommendation.

**Comment by hoony** [comment]
thanks for the comment @ottonomy :+1:

**Comment by simonwex** [comment]
I could convert the address to be a Google group we could all view if you
like? Otherwise, I'd say we just update it directly to @badgealliance.
Thoughts?

**Pull request closed without merging**
